### ISSUE TITLE
Update would fail if there's a space on path's name

### ISSUE THREAD

**Issue by jeda** [FocaBot/ytdl-getinfo#3]
Basically this, as one of the users showed in FocaBot's Lair:
![](https://cdn.discordapp.com/attachments/248272312665767947/418879506502123520/som_more.PNG)

After that, everything would simply fail.

**Comment by shortthirdman** [comment]
> Basically this, as one of the users showed in FocaBot's Lair:
> ![](https://camo.githubusercontent.com/61d2bc1cc698f58745853ce8effbfa6d674dbc0e57007cb3f337a76113cb18dd/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3234383237323331323636353736373934372f3431383837393530363530323132333532302f736f6d5f6d6f72652e504e47)
> 
> After that, everything would simply fail.

Still this issue, npm install fails during the updation of youtube-dl
