### ISSUE TITLE
Playlist JSON

### ISSUE THREAD

**Issue by sayem314** [FocaBot/ytdl-getinfo#4]
Only the first two videos json are dumped. why not allow more? Or give this as option.

**Comment by TheBITLINK** [comment]
When you load a playlist, only the first 2 videos are available initially. You have to listen for the `video` event for subsequent videos. Alternatively, you can listen for the `done` event to get the complete playlist. 

The README has an example for this:

```javascript
getInfo('PLwiyx1dc3P2JR9N8gQaQN_BCvlSlap7re').then(info => {
  // info.partial is true for playlists
  if (info.partial) {
    info.on('video', v => console.log(v.title))
    info.on('done', () => console.log(`Playlist contains ${info.items.length} items.`))
  }
})
```

**Comment by sayem314** [comment]
I see. I have used flag “wait = true” and seems to be working.
