### ISSUE TITLE
Add support for .version

### ISSUE THREAD

**Issue by sayem314** [FocaBot/ytdl-getinfo#5]
I guess title explains it well. It should display version about youtube-dl only.

**Comment by TheBITLINK** [comment]
I don't think i can add a `.version` parameter because that would cause additional delay (it requires a separate process call), but i can add a `.getVersion()` promise that resolves to the output of `youtube-dl --version`, sounds good?

**Comment by sayem314** [comment]
Yes man sounds good 👌

**Comment by TheBITLINK** [comment]
Done, update to `1.1.0`.

```javascript
require('ytdl-getinfo').getVersion().then(version => {
  console.log(`Current youtube-dl version: ${version}`)
})
```

**Comment by sayem314** [comment]
Awesome 👏

**Comment by sayem314** [comment]
And thank you 😊
